### PR TITLE
ScanPlanetOrMoonEvent misses systemAddress field 

### LINKED ISSUE #54: ScanPlanetOrMoonEvent misses systemAddress field
Hi there,
I think the ScanPlanetOrMoonEvent misses the systemAddress field (Long). It's included in the ScanStarEvent but I think it should be moved to the abstract ScanEvent. The event JSON provides it:

`
{ "timestamp":"2022-08-17T20:18:05Z", "event":"Scan", "ScanType":"Detailed", "BodyName":"LHS 2122 2", "BodyID":3, "Parents":[ {"Null":2}, {"Star":0} ], "StarSystem":"LHS 2122", "SystemAddress":7268561069481, "DistanceFromArrivalLS":564.383953, "TidalLock":true, "TerraformState":"", "PlanetClass":"Icy body", "Atmosphere":"", "AtmosphereType":"None", "Volcanism":"", "MassEM":0.142196, "Radius":4237765.000000, "SurfaceGravity":3.155900, "SurfaceTemperature":45.925526, "SurfacePressure":1.200703, "Landable":true, "Materials":[ { "Name":"sulphur", "Percent":22.654118 }, { "Name":"carbon", "Percent":19.049765 }, { "Name":"iron", "Percent":15.682040 }, { "Name":"phosphorus", "Percent":12.195987 }, { "Name":"nickel", "Percent":11.861238 }, { "Name":"chromium", "Percent":7.052734 }, { "Name":"manganese", "Percent":6.476522 }, { "Name":"zirconium", "Percent":1.821008 }, { "Name":"cadmium", "Percent":1.217781 }, { "Name":"tin", "Percent":1.020350 }, { "Name":"ruthenium", "Percent":0.968466 } ], "Composition":{ "Ice":0.676908, "Rock":0.217442, "Metal":0.105650 }, "SemiMajorAxis":109819138.050079, "Eccentricity":0.101043, "OrbitalInclination":-6.509743, "Periapsis":108.346898, "OrbitalPeriod":4451915.800571, "AscendingNode":179.527837, "MeanAnomaly":171.541899, "RotationPeriod":7909371.033029, "AxialTilt":-0.608184, "WasDiscovered":true, "WasMapped":true }`

See
https://github.com/SebastianSchlegel/EliteDangerousAPI/commit/037b54e6d00cee1a816f28861b1f6c7473958097
https://github.com/SebastianSchlegel/EliteDangerousAPI/commit/2ae65b298025b1b95c1970ea44334bc38172e102

I can open a pull request if you want.

Thanks for the good work with this API. I enjoy working with it!

BR
Sebastian

### PR DESCRIPTION
**Pull request by tastatortur**
fixes ChristopheCVB/EliteDangerousAPI#54

### CODE REVIEW

**Comment by ChristopheCVB** [comment]
I can also see that other fileds are missing from the ScanEvent and its children. Can you post the Json of the 3 different Scan events (Star, Planet and Moon) please, so we can also add there what is missing?
___________
Ah, maybe not, I had `WasMapped`, `WasDiscovered` in mind for example and it seems these are in ScanStarEvent class but they should be in the parent
___________
So yeah, having the 3 possible jsons would really help
___________
Here is the [Doc](https://elite-journal.readthedocs.io/en/latest/Exploration/#scan) I had when implementing the API, definitely not up to date

**Comment by tastatortur** [comment]
Here are some Scan events. I think the difference between moons and planets are only in their parent.

star:
`{ "timestamp":"2022-02-06T19:02:57Z", "event":"Scan", "ScanType":"NavBeaconDetail", "BodyName":"Nemehi A", "BodyID":1, "Parents":[ {"Null":0} ], "StarSystem":"Nemehi", "SystemAddress":4511619877227, "DistanceFromArrivalLS":0.000000, "StarType":"F", "Subclass":7, "StellarMass":1.078125, "Radius":746694592.000000, "AbsoluteMagnitude":4.289703, "Age_MY":5520, "SurfaceTemperature":6315.000000, "Luminosity":"Vb", "SemiMajorAxis":4325259327888.488770, "Eccentricity":0.047310, "OrbitalInclination":-21.008289, "Periapsis":148.606488, "OrbitalPeriod":31232251524.925232, "RotationPeriod":316876.316831, "AxialTilt":0.000000, "Rings":[ { "Name":"Nemehi A A Belt", "RingClass":"eRingClass_Metalic", "MassMT":4.4288e+07, "InnerRad":1.4334e+09, "OuterRad":2.4743e+09 } ], "WasDiscovered":false, "WasMapped":false }`

belt:
`{ "timestamp":"2022-02-06T19:02:57Z", "event":"Scan", "ScanType":"NavBeaconDetail", "BodyName":"Nemehi B A Belt Cluster 2", "BodyID":18, "Parents":[ {"Ring":16}, {"Star":2}, {"Null":0} ], "StarSystem":"Nemehi", "SystemAddress":4511619877227, "DistanceFromArrivalLS":55151.995273, "WasDiscovered":false, "WasMapped":false }`

moon:
`{ "timestamp":"2022-02-06T19:02:57Z", "event":"Scan", "ScanType":"NavBeaconDetail", "BodyName":"Nemehi B 3 a", "BodyID":54, "Parents":[ {"Planet":52}, {"Null":42}, {"Star":2}, {"Null":0} ], "StarSystem":"Nemehi", "SystemAddress":4511619877227, "DistanceFromArrivalLS":56510.630867, "TidalLock":true, "TerraformState":"", "PlanetClass":"Icy body", "Atmosphere":"", "AtmosphereType":"None", "Volcanism":"major water geysers volcanism", "MassEM":0.001900, "Radius":1091484.250000, "SurfaceGravity":0.635752, "SurfaceTemperature":77.681717, "SurfacePressure":0.000000, "Landable":true, "Materials":[ { "Name":"sulphur", "Percent":26.896494 }, { "Name":"carbon", "Percent":22.617167 }, { "Name":"phosphorus", "Percent":14.479897 }, { "Name":"iron", "Percent":12.090105 }, { "Name":"nickel", "Percent":9.144449 }, { "Name":"chromium", "Percent":5.437322 }, { "Name":"selenium", "Percent":4.209529 }, { "Name":"vanadium", "Percent":2.968909 }, { "Name":"tellurium", "Percent":0.904971 }, { "Name":"tin", "Percent":0.723195 }, { "Name":"mercury", "Percent":0.527955 } ], "Composition":{ "Ice":0.824755, "Rock":0.159551, "Metal":0.015694 }, "SemiMajorAxis":149597978.591919, "Eccentricity":0.000306, "OrbitalInclination":0.039012, "Periapsis":198.575944, "OrbitalPeriod":128707.224131, "RotationPeriod":128715.781411, "AxialTilt":0.513400, "WasDiscovered":false, "WasMapped":true }`

planet:
`{ "timestamp":"2022-02-06T19:02:57Z", "event":"Scan", "ScanType":"NavBeaconDetail", "BodyName":"Nemehi A 4", "BodyID":10, "Parents":[ {"Star":1}, {"Null":0} ], "StarSystem":"Nemehi", "SystemAddress":4511619877227, "DistanceFromArrivalLS":198.291244, "TidalLock":false, "TerraformState":"", "PlanetClass":"High metal content body", "Atmosphere":"", "AtmosphereType":"None", "Volcanism":"major rocky magma volcanism", "MassEM":1.239130, "Radius":6475204.500000, "SurfaceGravity":11.779298, "SurfaceTemperature":459.064453, "SurfacePressure":0.000000, "Landable":true, "Materials":[ { "Name":"iron", "Percent":21.714172 }, { "Name":"nickel", "Percent":16.423689 }, { "Name":"sulphur", "Percent":15.352349 }, { "Name":"carbon", "Percent":12.909736 }, { "Name":"chromium", "Percent":9.765584 }, { "Name":"manganese", "Percent":8.967731 }, { "Name":"phosphorus", "Percent":8.265035 }, { "Name":"selenium", "Percent":2.402772 }, { "Name":"niobium", "Percent":1.484048 }, { "Name":"molybdenum", "Percent":1.417923 }, { "Name":"yttrium", "Percent":1.296962 } ], "Composition":{ "Ice":0.000000, "Rock":0.667243, "Metal":0.332757 }, "SemiMajorAxis":59417542219.161987, "Eccentricity":0.000582, "OrbitalInclination":-0.133012, "Periapsis":130.633020, "OrbitalPeriod":7606767.773628, "RotationPeriod":-7607049.740340, "AxialTilt":2.752556, "WasDiscovered":false, "WasMapped":true }`

gas giant with rings:
`{ "timestamp":"2022-02-06T19:02:57Z", "event":"Scan", "ScanType":"NavBeaconDetail", "BodyName":"Nemehi B 3", "BodyID":52, "Parents":[ {"Null":42}, {"Star":2}, {"Null":0} ], "StarSystem":"Nemehi", "SystemAddress":4511619877227, "DistanceFromArrivalLS":56510.192005, "TidalLock":true, "TerraformState":"", "PlanetClass":"Sudarsky class I gas giant", "Atmosphere":"", "AtmosphereComposition":[ { "Name":"Hydrogen", "Percent":73.708252 }, { "Name":"Helium", "Percent":26.291761 } ], "Volcanism":"", "MassEM":20.014957, "Radius":40169544.000000, "SurfaceGravity":4.943907, "SurfaceTemperature":86.812225, "SurfacePressure":0.000000, "Landable":false, "SemiMajorAxis":10785532593.727112, "Eccentricity":0.134998, "OrbitalInclination":9.889981, "Periapsis":300.230592, "OrbitalPeriod":22696154.713631, "RotationPeriod":23500989.775603, "AxialTilt":-0.211021, "Rings":[ { "Name":"Nemehi B 3 A Ring", "RingClass":"eRingClass_Icy", "MassMT":1.0994e+11, "InnerRad":7.2708e+07, "OuterRad":9.4521e+07 } ], "ReserveLevel":"CommonResources", "WasDiscovered":false, "WasMapped":true }`

**Review by ChristopheCVB — DISMISSED** [review]
Nice!
I'll wait for this to release 1.0.2

**Comment by ChristopheCVB** [comment]
Is there anything else or can I merge this?

**Comment by ChristopheCVB** [comment]
@SebastianSchlegel Is there anything else or can I merge this?

**Review by ChristopheCVB — APPROVED** [review]

**Comment by tastatortur** [comment]
Hi @ChristopheCVB, sorry for messing around with this pull request. Accidentally clicked on "request review" and tried to revert it. Whatever, I think you knwo what to do with it ;-)

**Review by ChristopheCVB — APPROVED** [review]

**Pull request merged**
